### ISSUE TITLE
sdist missing requirement files

### ISSUE THREAD

**Issue by adamjstewart** [lightly-ai/lightly#1146]
At the moment, it isn't possible to install lightly from an [sdist](https://files.pythonhosted.org/packages/5e/9b/c885ceabb01c4fecf95ab09000484a0c908b6e502b27fb2e115cfd7e2fb1/lightly-1.4.1.tar.gz) tarball, you either have to install from git or from a wheel. Would it be possible to add the requirements directory to the sdist that gets generated?

**Comment by philippmwirth** [comment]
I can reproduce with the attached file. Currently getting the following error:
```
Processing ./lightly-1.4.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpj3kj7pf2 get_requires_for_build_wheel /tmp/tmp9puxcc4n
       cwd: /tmp/pip-req-build-yajjo13l
  Complete output (19 lines):
  Partial import of lightly==1.4.1 during build process.
  Traceback (most recent call last):
    File "/tmp/tmpj3kj7pf2", line 280, in <module>
      main()
    File "/tmp/tmpj3kj7pf2", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpj3kj7pf2", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-i8k60ni4/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-i8k60ni4/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-i8k60ni4/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-i8k60ni4/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 65, in <module>
    File "<string>", line 19, in load_description
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-yajjo13l/DOCS.md'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpj3kj7pf2 get_requires_for_build_wheel /tmp/tmp9puxcc4n Check the logs for full command output.
```

It looks like the problem is that `setup.py` relies on certain files that are not included in the source distribution. This should be relatively easy to fix by adding `package_data`. 

Is there a particular reason you're trying to install from source? It's generally recommended to install from wheel files if possible.

**Comment by adamjstewart** [comment]
I'm a developer for the Spack package manager. We generally try to build all packages from source.

**Comment by guarin** [comment]
@adamjstewart is this still an issue?
