### ISSUE TITLE
Importing anything raises DeprecationWarning

### ISSUE THREAD

**Issue by adamjstewart** [lightly-ai/lightly#1152]
This seems to be an unintended consequence of #1121.

### Steps to reproduce

```console
$ python -Werror -c 'import lightly'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Adam/spack/opt/spack/darwin-ventura-m2/apple-clang-14.0.3/py-lightly-1.4.1-gxvczr6frj5qr5akidp5xo7jsipulurg/lib/python3.10/site-packages/lightly/__init__.py", line 125, in <module>
    from lightly.api.version_checking import (
  File "/Users/Adam/spack/opt/spack/darwin-ventura-m2/apple-clang-14.0.3/py-lightly-1.4.1-gxvczr6frj5qr5akidp5xo7jsipulurg/lib/python3.10/site-packages/lightly/api/__init__.py", line 7, in <module>
    from lightly.api.api_workflow_client import ApiWorkflowClient
  File "/Users/Adam/spack/opt/spack/darwin-ventura-m2/apple-clang-14.0.3/py-lightly-1.4.1-gxvczr6frj5qr5akidp5xo7jsipulurg/lib/python3.10/site-packages/lightly/api/api_workflow_client.py", line 19, in <module>
    from lightly.api.api_workflow_selection import _SelectionMixin
  File "/Users/Adam/spack/opt/spack/darwin-ventura-m2/apple-clang-14.0.3/py-lightly-1.4.1-gxvczr6frj5qr5akidp5xo7jsipulurg/lib/python3.10/site-packages/lightly/api/api_workflow_selection.py", line 7, in <module>
    from lightly.active_learning.config.selection_config import SelectionConfig
  File "/Users/Adam/spack/opt/spack/darwin-ventura-m2/apple-clang-14.0.3/py-lightly-1.4.1-gxvczr6frj5qr5akidp5xo7jsipulurg/lib/python3.10/site-packages/lightly/active_learning/__init__.py", line 14, in <module>
    raise_active_learning_deprecation_warning()
  File "/Users/Adam/spack/opt/spack/darwin-ventura-m2/apple-clang-14.0.3/py-lightly-1.4.1-gxvczr6frj5qr5akidp5xo7jsipulurg/lib/python3.10/site-packages/lightly/active_learning/__init__.py", line 5, in raise_active_learning_deprecation_warning
    warnings.warn(
DeprecationWarning: Using active learning via the lightly package is deprecated and will be removed soon. Please use the Lightly Solution instead. See https://docs.lightly.ai for more information and tutorials on doing active learning.
```
This warning should only be raised when a user is actually using a deprecated feature.

@MalteEbner @huan-lightly-0

**Comment by guarin** [comment]
Should be fixed by #1154
