### ISSUE TITLE
[Active Learning] Added directories not added to setup.py

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#159]
In the `setup.py`, all directories being part of lightly need to be listed:
https://github.com/lightly-ai/lightly/blob/7c4c99b5e5ea5eb5025e173b8aa20646e63573cd/setup.py#L77-L96

However, the new directories `lightly/active_learning` and `lightly/openapi_generated` are not listed.
This causes errors when trying to use the package distributed as an egg from the CLI, such as 
```
malteebnerlightly@MacBook-Pro-16-Malte datasets % lightly-embed --version
Traceback (most recent call last):
  File "/usr/local/bin/lightly-embed", line 5, in <module>
    from lightly.cli.embed_cli import entry
  File "/usr/local/lib/python3.9/site-packages/lightly/__init__.py", line 101, in <module>
    from lightly.core import train_model_and_embed_images
  File "/usr/local/lib/python3.9/site-packages/lightly/core.py", line 6, in <module>
    from lightly.cli.train_cli import _train_cli
  File "/usr/local/lib/python3.9/site-packages/lightly/cli/__init__.py", line 9, in <module>
    from lightly.cli.lightly_cli import lightly_cli
  File "/usr/local/lib/python3.9/site-packages/lightly/cli/lightly_cli.py", line 15, in <module>
    from lightly.cli.upload_cli import _upload_cli
  File "/usr/local/lib/python3.9/site-packages/lightly/cli/upload_cli.py", line 15, in <module>
    from lightly.api.utils import getenv
  File "/usr/local/lib/python3.9/site-packages/lightly/api/__init__.py", line 8, in <module>
    from lightly.api.upload import upload_images_from_folder    # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/lightly/api/upload.py", line 27, in <module>
    from lightly.openapi_generated.swagger_client.configuration import Configuration
ModuleNotFoundError: No module named 'lightly.openapi_generated'
```

**Comment by philippmwirth** [comment]
Close this?
