### ISSUE TITLE
RuntimeError: Forbidden upload to dataset with no existing tags

### ISSUE THREAD

**Issue by Samjith888** [lightly-ai/lightly#40]
Got the following error while uploading embedding 

### Command used 
` lightly-upload token='' dataset_id='' embeddings='/home/usr/embeddings.csv'`

### Error 

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/effd/lib/python3.7/site-packages/lightly/cli/upload_cli.py", line 107, in upload_cli
    _upload_cli(cfg)
  File "/home/ubuntu/anaconda3/envs/effd/lib/python3.7/site-packages/lightly/cli/upload_cli.py", line 52, in _upload_cli
    embedding_name=cfg['embedding_name']
  File "/home/ubuntu/anaconda3/envs/effd/lib/python3.7/site-packages/lightly/api/upload.py", line 115, in upload_embeddings_from_csv
    raise RuntimeError(msg)
RuntimeError: Forbidden upload to dataset with no existing tags.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by philippmwirth** [comment]
Did you upload your dataset first? If not, please try one of the following:
```
# upload full images
lightly-upload token='' dataset_id='' input_dir='path/to/your/images' 

# upload thumbnails only (for privacy reasons)
lightly-upload token='' dataset_id='' input_dir='path/to/your/images' upload='thumbnails'

# upload metadata only (for privacy reasons)
lightly-upload token='' dataset_id='' input_dir='path/to/your/images' upload='metadata'
```

Then, retry the command above and it should work now.

In case you did, it may be that something went wrong during the upload. Could you, in that case, show me the exact command you used for uploading the images?
