### ISSUE TITLE
Error: number of embeddings does not match number of samples

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#400]
I got an error while using `lightly-magic` on a larger dataset.
My gut feeling tells me that this could be related to the number of workers or the batch size. Let's debug and fix the issue :)

I used the following command:
```
lightly-magic token='TOKEN' dataset_id='DATASET_ID' input_dir=/datasets/data trainer.max_epochs=40 loader.batch_size=256  loader.num_workers=12
```

The dataset consists of `74202` images.

```
Epoch 39: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 289/289 [02:24<00:00,  2.00it/s, loss=4.66, v_num=0]
Best model is stored at: /datasets/lightly_outputs/2021-06-07/07-44-35/lightly_epoch_9.ckpt                                                                            
########## Starting to embed your dataset.
Compute efficiency: 0.03: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:31<00:00,  9.25it/s]
Embeddings are stored at /datasets/lightly_outputs/2021-06-07/07-44-35/embeddings.csv                                                                                  
########## Starting to upload your dataset to the Lightly platform.
Uploading images (with 12 workers).
  0%|▏                                                                                                                                     | 99/74202 [00:09<1:31:21, 13.52imgs/s]/opt/conda/envs/lightly/lib/python3.7/site-packages/lightly_utils/image_processing/metadata.py:53: RuntimeWarning: divide by zero encountered in double_scalars                  
  return float(np.where(std == 0., 0, mean / std))
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 74202/74202 [3:47:52<00:00,  4.35imgs/s]Finished the upload of the dataset.
Starting upload of embeddings.
Traceback (most recent call last):
  File "/opt/conda/envs/lightly/lib/python3.7/site-packages/lightly/cli/lightly_cli.py", line 80, in lightly_cli                                                                 
    return _lightly_cli(cfg)
  File "/opt/conda/envs/lightly/lib/python3.7/site-packages/lightly/cli/lightly_cli.py", line 38, in _lightly_cli                                                                
    _upload_cli(cfg)
  File "/opt/conda/envs/lightly/lib/python3.7/site-packages/lightly/cli/upload_cli.py", line 76, in _upload_cli                                                                  
    path_to_embeddings_csv=path_to_embeddings, name=name
  File "/opt/conda/envs/lightly/lib/python3.7/site-packages/lightly/api/api_workflow_upload_embeddings.py", line 71, in upload_embeddings                                        
    path_to_embeddings_csv=path_to_embeddings_csv)
  File "/opt/conda/envs/lightly/lib/python3.7/site-packages/lightly/api/api_workflow_upload_embeddings.py", line 104, in _order_csv_by_filenames                                 
    raise ValueError(f'There are {len(filenames)} rows in the embedding file, but '
ValueError: There are 74202 rows in the embedding file, but 74208 filenames/samples on the server.                                                                               

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 74202/74202 [3:48:50<00:00,  5.40imgs/s]
```

**Comment by MalteEbner** [comment]
I assume the problem lies in 
https://github.com/lightly-ai/lightly/blob/ffabd63bd340c1cc69def46b3c772dcfc783efa4/lightly/api/api_workflow_upload_dataset.py#L163-L168

If this function is retried, multiple samples are created on the backend side for the same sample in the lightly package.

One general solution to this problem would be the following change:
If an upload_url is requested for a filename, which already exists on the server, not a new url, but the existing url is returned. Then it would not even cause errors if you start an upload, stop it, and start the new upload from the beginning.

**Comment by MalteEbner** [comment]
A solution only on the pip side would be the following:
- before the upload: get the filenames of all samples already uploaded with getSamplesByDatasetId
- skip all samples having a filename already uploaded

Advantages:
- Solves the problem of stopping and continuing the upload, this is handled
- very little overhead, as only one additional API call
- as usually the dataset is empty, this call should return fast

Disadvantages:
- requires unique filenames
- does not handle errors after creating the sample, but not uploading the thumbname/image

**Comment by robmarkcole** [comment]
I can report this issue on latest:

```
########## Starting to upload your dataset to the Lightly platform.
Uploading images (with 2 workers).
100% 10000/10000 [2:47:28<00:00,  1.00s/imgs]
Finished the upload of the dataset.
Starting upload of embeddings.
Error executing job with overrides: ['token=xx', 'dataset_id=x', 'input_dir=/content/drive/MyDrive/data/xx/', 'trainer.max_epochs=20', '++collate.rr_prob=0.5', '++collate.vf_prob=0.5']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/lightly/cli/lightly_cli.py", line 87, in lightly_cli
    return _lightly_cli(cfg)
  File "/usr/local/lib/python3.7/dist-packages/lightly/cli/lightly_cli.py", line 38, in _lightly_cli
    _upload_cli(cfg)
  File "/usr/local/lib/python3.7/dist-packages/lightly/cli/upload_cli.py", line 140, in _upload_cli
    path_to_embeddings_csv=path_to_embeddings, name=name
  File "/usr/local/lib/python3.7/dist-packages/lightly/api/api_workflow_upload_embeddings.py", line 82, in upload_embeddings
    path_to_embeddings_csv=path_to_embeddings_csv)
  File "/usr/local/lib/python3.7/dist-packages/lightly/api/api_workflow_upload_embeddings.py", line 197, in _order_csv_by_filenames
    raise ValueError(f'There are {len(filenames)} rows in the embedding file, but '
ValueError: There are 10000 rows in the embedding file, but 10001 filenames/samples on the server.
```

**Comment by philippmwirth** [comment]
This should be resolved by changes we made on the API side. Feel free to re-open this if the error should come up again.
