### ISSUE TITLE
hydra error

### ISSUE THREAD

**Issue by wajeehDarvis** [lightly-ai/lightly#679]
After pulling the image when I ry to run it i get the following error.

Traceback (most recent call last):
  File "main.py", line 1496, in <module>
    main(None)
  File "/opt/conda/envs/env/lib/python3.7/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/opt/conda/envs/env/lib/python3.7/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/opt/conda/envs/env/lib/python3.7/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/opt/conda/envs/env/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/opt/conda/envs/env/lib/python3.7/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/opt/conda/envs/env/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 104, in run
    run_mode=RunMode.RUN,
  File "/opt/conda/envs/env/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 512, in compose_config
    from_shell=from_shell,
  File "/opt/conda/envs/env/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 156, in load_configuration
    from_shell=from_shell,
  File "/opt/conda/envs/env/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 180, in _load_configuration
    parsed_overrides = parser.parse_overrides(overrides=overrides)
  File "/opt/conda/envs/env/lib/python3.7/site-packages/hydra/core/override_parser/overrides_parser.py", line 99, in parse_overrides
    ) from e.__cause__
hydra.errors.OverrideParseException: Error parsing override '/bin/bash'
extraneous input '/' expecting {'~', '+', DOT_PATH, ID}
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

**Comment by psp313** [comment]
error: /lib/x86_64-linux-gnu/libmongoc-1.0.so.0

**Comment by philippmwirth** [comment]
Hi @wajeehDarvis, we have investigated the problem and it seems you're trying to run the image with the custom entry point `/bin/bash`. However, this is not the intended way of running the image. Please consult the [docs for further information](https://docs.lightly.ai/docker/getting_started/first_steps.html). We will add a clearer error message in one of the upcoming releases.
